---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: fahmy-system
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: root
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: example
        - name: ME_CONFIG_OPTIONS_EDITORTHEME
          value: ambiance
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongodb-lb.fahmy-system.svc.cluster.local

---
apiVersion: v1
kind: Service
metadata:
  namespace: fahmy-system
  name: mongo-express-lb
  labels:
    app: mongo-express-lb
spec:
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001
  type: LoadBalancer