---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-storage
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
  hostPath:
    path: "/home/fahmyabdul/.strg_kube/mongodb"
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mongodb-claim
    namespace: fahmy-system

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: fahmy-system
  name: mongodb-claim
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  - ReadOnlyMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: openebs-hostpath
  volumeMode: Filesystem
  volumeName: mongodb-storage

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: fahmy-system
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: example
        volumeMounts:
        - mountPath: /data
          name: mongo-vol-1
      volumes:
      - name: mongo-vol-1
        persistentVolumeClaim:
          claimName: mongodb-claim
          
---
apiVersion: v1
kind: Service
metadata:
  namespace: fahmy-system
  name: mongodb-lb
  labels:
    app: mongodb-lb
spec:
  selector:
    app: mongodb
  loadBalancerIP: 192.168.49.1
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30000
  type: LoadBalancer