---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-storage
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
  hostPath:
    path: "/home/fahmyabdul/.strg_kube/mysql"
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mysql-claim
    namespace: fahmy-system

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: fahmy-system
  name: mysql-claim
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  - ReadOnlyMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: openebs-hostpath
  volumeMode: Filesystem
  volumeName: mysql-storage

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: fahmy-system
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: example
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-vol-1
      volumes:
      - name: mysql-vol-1
        persistentVolumeClaim:
          claimName: mysql-claim
          
---
apiVersion: v1
kind: Service
metadata:
  namespace: fahmy-system
  name: mysql-lb
  labels:
    app: mysql-lb
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30002
  type: LoadBalancer