---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-storage
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/fahmyabdul/.strg_kube/redis/data"
  capacity:
    storage: 2Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: redis-data-claim
    namespace: fahmy-system

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: fahmy-system
  name: redis-data-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: openebs-hostpath
  volumeMode: Filesystem
  volumeName: redis-data-storage

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: fahmy-system
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      initContainers:
      - name: config
        image: redis:7.0.5-alpine
        command: [ "sh", "-c" ]
        args:
          - |
            cp /tmp/redis/redis.conf /etc/redis/redis.conf
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis/
        - name: config
          mountPath: /tmp/redis/
      containers:
      - name: redis
        image: redis:7.0.5-alpine
        command: ["redis-server"]
        args: ["/etc/redis/redis.conf"]
        volumeMounts:
        - mountPath: /data
          name: redis-data-1
        - mountPath: /etc/redis/
          name: redis-config
      volumes:
      - name: redis-data-1
        persistentVolumeClaim:
          claimName: redis-data-claim
      - name: redis-config
        emptyDir: {}
      - name: config
        configMap:
          name: redis-config
          
---
apiVersion: v1
kind: Service
metadata:
  namespace: fahmy-system
  name: redis-lb
  labels:
    app: redis-lb
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 30003
  type: LoadBalancer