---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-storage
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
  hostPath:
    path: "/home/fahmyabdul/.strg_kube/kafka"
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: kafka-claim
    namespace: fahmy-system

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: fahmy-system
  name: kafka-claim
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: openebs-hostpath
  volumeMode: Filesystem
  volumeName: kafka-storage

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: fahmy-system
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: docker.io/bitnami/kafka:3.3
        env:
          - name: KAFKA_CFG_ZOOKEEPER_CONNECT
            value: zookeeper-lb.fahmy-system.svc.cluster.local:2181
          - name: ALLOW_PLAINTEXT_LISTENER
            value: "yes"
          - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
            value: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
          - name: KAFKA_CFG_LISTENERS
            value: CLIENT://:9092,EXTERNAL://:9093
          - name: KAFKA_CFG_ADVERTISED_LISTENERS
            value: CLIENT://kafka-lb.fahmy-system.svc.cluster.local:9092,EXTERNAL://<load-balancer-ip>:9093
          - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
            value: CLIENT
          - name: KAFKA_DEFAULT_REPLICATION_FACTOR
            value: "1"
        volumeMounts:
        - mountPath: /bitnami
          name: kafka-vol-1
      volumes:
      - name: kafka-vol-1
        persistentVolumeClaim:
          claimName: kafka-claim
          
---
apiVersion: v1
kind: Service
metadata:
  namespace: fahmy-system
  name: kafka-lb
  labels:
    app: kafka-lb
spec:
  selector:
    app: kafka
  ports:
    - name: 'internal-access'
      nodePort: 30004
      port: 9092
      protocol: TCP
      targetPort: 9092
    - name: 'external-access'
      nodePort: 30006
      port: 9093
      protocol: TCP
      targetPort: 9093
  type: LoadBalancer