---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-storage
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
  hostPath:
    path: "/home/fahmyabdul/.strg_kube/zookeeper"
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: zookeeper-claim
    namespace: fahmy-system

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: fahmy-system
  name: zookeeper-claim
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: openebs-hostpath
  volumeMode: Filesystem
  volumeName: zookeeper-storage

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: fahmy-system
  name: zookeeper
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: docker.io/bitnami/zookeeper:3.8
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        volumeMounts:
        - mountPath: /bitnami
          name: zookeeper-vol-1
      volumes:
      - name: zookeeper-vol-1
        persistentVolumeClaim:
          claimName: zookeeper-claim
          
---
apiVersion: v1
kind: Service
metadata:
  namespace: fahmy-system
  name: zookeeper-lb
  labels:
    app: zookeeper-lb
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
      nodePort: 30005
  type: LoadBalancer